netlify/next-on-netlify

README.md, lib/collectNextjsPages.js, lib/getNetlifyRoute.js, lib/serverless-next.js/expressifyDynamicRoute.js, lib/serverless-next.js/isDynamicRoute.js, lib/serverless-next.js/pathToRegexStr.js, lib/serverless-next.js/prepareBuildManifests.js, lib/serverless-next.js/readPagesManifest.js, lib/serverless-next.js/sortedRoutes.js
This is re-opening the pull request proposed by @spencewood. I accidentally messed up their pull request #1  :see_no_evil: I'll keep my fingers off force pushing from now on...
> @spencewood:
> This simply pulls in the latest code from https://github.com/danielcondemarin/serverless-next.js/blob/master/packages/serverless-nextjs-component/lib/expressifyDynamicRoute.js which supports dynamic catch all routes.
=> Catch-all routes (reopening of PR#1)

lib/allNextJsPages.js, lib/setupRedirects.js, lib/setupSsgPages.js, package-lock.json, tests/__snapshots__/defaults.test.js.snap, tests/defaults.test.js, tests/fixtures/pages-with-static-props-index/index.js, tests/fixtures/pages-with-static-props-index/static/index.js, tests/staticIndexPages.test.js
Previously, the / route having associated data would cause the
build to fail as it would attempt to reference an /.html file
instead of /index.html
This also fixes a stability issue with the snapshot test for
_redirects, which are not necessarily generated in a stable order.
=> Allow the main index route to be ssg rendered with getStaticProps

README.md, lib/config.js, lib/setupRedirects.js, tests/customRedirects.test.js
Since _redirects always takes precedence over netlify.toml,
allowing a custom _redirects file to be prepended to the
published one is the only way to force a redirect of a path that
matches content handled by next-on-netlify. This can be
useful when using netlify to redirect from one domain to another.
=> Add support for a custom _redirects file

README.md
I'm getting into this project (great stuff, by the way!) and I've noticed a missing link in the docs so I figured - might as well add it 🎉
=> Adding a missing link to serverless next.js docs

lib/allNextJsPages.js
When adding `getServerSideProps` to `index.js`, `next-on-netlify` would add
```
/_next/data/.../.json  /.netlify/functions/next_index  200
```
to the `out_publish/_redirects` file. 
I added a fix so that
```
/_next/data/.../index.json  /.netlify/functions/next_index  200
``` 
will be written instead.
=> Fixed redirect for index with getServerSideProps

lib/allNextJsPages.js, tests/fixtures/pages/getStaticProps/dynamic.js, tests/fixtures/pages/getStaticProps/ssg/[id].js
Proposal to use SSR for incremental static regeneration (https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration).
This is definitely no production code, but I would like to determine how incremental static regeneration could be added.
=> Proposal to use SSR for incremental static regeneration

lib/templates/netlifyFunction.js
extends/fixes conflict in https://github.com/netlify/next-on-netlify/pull/42
---
Hi everyone, looking for a solution to to resolve #40 I did my fork, and case this is acceptable in the project, I will let my PR 😄
This PR takes the host property from event.headers and copy to host in event.multiValueHeaders.
I'm opening this PR just in case you think this a good way to solve this problem.
PS: If you think that has another way, just give the suggest and I will take a look and implement.
PS: I don't know if this change specifically needs some test, if need, what exactly I can test.
=> Copy host property from headers to multiValueHeaders

lib/constants/regex.js, lib/helpers/getNetlifyRoutes.js, lib/helpers/isRootCatchAllRedirect.js, lib/steps/setupRedirects.js, package.json, tests/__snapshots__/optionalCatchAll.test.js.snap
Fixes https://github.com/netlify/next-on-netlify/issues/43
=> [fix] page chunk for root level catch-all is served incorrectly to client

lib/templates/netlifyFunction.js
Fixes https://github.com/netlify/next-on-netlify/issues/46
=> Fix: x-forwarded-host is undefined on Netlify

lib/steps/prepareFolders.js
Just looking into the code to better understand and this popped out to me, I think the path constants are backwards here.
=> Logs correct path constants

README.md
This change in the readme is to help future developers not have binary issues across lambda functions created by the next build command.
=> Update to prevent #55 from occurring again

lib/steps/setupRedirects.js, tests/__snapshots__/defaults.test.js.snap, tests/__snapshots__/optionalCatchAll.test.js.snap
=> remove the temporary splat workaround now that internal fix is released

lib/helpers/isRootCatchAllRedirect.js
Hi @lindsaylevine,
This fix seems to work for the issue reported in https://github.com/netlify/next-on-netlify/issues/43#issuecomment-726562484
=> Update isRootCatchAllRedirect condition

.github/workflows/workflow.yml
This adds CI tests using GitHub actions copied from other Netlify projects.
This also allows us testing this code on Windows, which is important since many Netlify CLI users are on Windows. Tests on Windows are currently not enabled though, since they fail at the moment. We can add support for Windows in a follow-up PR.
Node `<12` does not seem to be currently supported, so CI tests are only running on Node 12 and 14. In a follow-up PR, we can add support for older Node.js versions, so it matches Netlify's officially supported Node.js versions.
=> Add CI tests

.github/workflows/workflow.yml, package.json, tests/helpers/buildNextApp.js
Node `10.17.0` could not run tests due to a test helpers using a JavaScript feature added in Node 12 (instance fields).
This PR fixes this.
It also runs tests on Node `10.17.0` and adds `engines.node` to declare the supported Node.js versions.
=> Add support for Node `10.17.0`.

index.js, lib/helpers/getNextConfig.js, lib/helpers/getNextDistDir.js, lib/helpers/setupNetlifyFunctionForPage.js, lib/helpers/setupStaticFileForPage.js, lib/pages/api/setup.js, lib/pages/getInitialProps/setup.js, lib/pages/getServerSideProps/setup.js, lib/pages/getStaticProps/setup.js, lib/pages/getStaticPropsWithFallback/setup.js, lib/pages/getStaticPropsWithRevalidate/setup.js, lib/pages/withoutProps/setup.js, lib/steps/copyNextAssets.js, lib/steps/copyPublicFiles.js, lib/steps/prepareFolders.js, lib/steps/setupPages.js, lib/steps/setupRedirects.js
cc: @FinnWoelm 
this is needed for https://github.com/netlify/netlify-plugin-nextjs/issues/43
=> use configurable functionsDir and publishDir throughout NoN

package.json
This upgrades the version range of `next`, following the discussion at https://github.com/netlify/netlify-plugin-nextjs/issues/25
See also https://github.com/netlify/netlify-plugin-nextjs/issues/42
I.e. `next-on-netlify` will not prevent Next.js 10 users from using this, but support is currently experimental.
=> Upgrade version range of `next`

.github/workflows/workflow.yml
Fixed #87.
Unfortunately, we need to use Node `10.15.0` and not `10.13.0` because Jest `>=25` [has a bug with Node `<10.15.0`](https://github.com/facebook/jest/issues/9453), so that would force us to downgrade Jest two major releases down.
However, we should be just fine with testing `10.15.0`, not many big changes happened in-between those two versions.
=> Fix Node.js version in CI

README.md
We recently migrated our nextjs website for gemini.com to use next-on-netlify from aws and would love to be showcased! This plugin really makes our every day life easier!
=> Add gemini.com to showcase

cypress/fixtures/pages/api/redirect.js, cypress/integration/default_spec.js, lib/templates/createResponseObject.js
:warning: **MERGE THIS PR AFTER #92** :warning: 
This PR adds support for `res.redirect` in API routes as described in https://nextjs.org/docs/api-routes/response-helpers
It does this by returning the `res` object from `res.writeHead`, thus allowing method chaining. This is how a ServerResponse object should behave according to https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers. The other mock methods of the `res` object probably need to be adjusted in the future, too.
This PR resolves #74 (thanks for the test case, @afzalsayed96! It's the first commit in this PR :slightly_smiling_face: ).
=> Fix: Add support for res.redirect in API routes

lib/steps/prepareFolders.js
required for https://github.com/netlify/netlify-plugin-nextjs/pull/49
=> fix: dont empty publish/function paths unless theyre default

README.md
next-cms-ghost is an open-source blog starter powered by Next.js and headless Ghost CMS. Thanks to the next-on-netlify plugin, we are now able to offer one-click Netlify deploys. @lindsaylevine: Thanks for considering to add this use-case to the showcase section.
=> Add next-cms-ghost to showcase

lib/templates/createResponseObject.js
This signals to Next that we aren't expecting any props to be returned in `getServersideProps` or `getInitialProps`
Fixes: https://github.com/netlify/next-on-netlify/issues/116
I might've made a mistake to submit this PR from the GH-edit-UI, the labels didn't carry over 😅 
I've also added `writeableEnded` because [`finished` is deprecated](https://nodejs.org/api/http.html#http_response_finished)
=> Add finished to res

cypress/integration/optionalCatchAll_at_root_spec.js
This fixes a failing test when running `npm run cypress:local`.
The failing test is testing the cache control header of a pre-rendered, static page and expecting the headers to include "public". This is the case on netlify.app. However, in netlify dev this cache control header is not present, causing the test to fail.
For now, we simply skip the test when running the Cypress tests locally (as we do in `default_spec.js`). In the long term, we should probably set headers in a `_headers` file as suggested by https://github.com/netlify/next-on-netlify/issues/110.
=> Fix cypress:local: Skip test for cache control header

README.md, cypress/fixtures/pages/api/context.js, cypress/fixtures/pages/getServerSideProps/context.js, cypress/fixtures/pages/getServerSideProps/wait-on-empty-event-loop/[wait].js, cypress/integration/default_spec.js, lib/templates/createRequestObject.js, lib/templates/netlifyFunction.js, lib/templates/renderNextPage.js
When a page is being SSR-ed by a Netlify Function, allow users to access the function's event and context parameters. These can be accessed as a property on the `req` object in all SSR-ed pages and in API routes:
- req.netlifyFunction.event
- req.netlifyFunction.context
```js
const Page = () => <p>Hello World!</p>;
export const getServerSideProps = async ({ req }) => {
// Get event and context from Netlify Function
const {
netlifyFunction: { event, context },
} = req;
// Access Netlify identity
const { identity, user } = context.clientContext;
// Modify callbackWaitsForEmptyEventLoop behavior
context.callbackWaitsForEmptyEventLoop = false;
// See how much time is remaining before function timeout
const timeRemaining = context.getRemainingTimeInMillis();
return {
props: {},
};
};
export …
```
=> Expose event and context of Netlify Function in Next.js pages and API routes

lib/steps/setupRedirects.js
if we hate this, we can update it in the future. right now i want to release the plugin and this was blocking the plugin tests - redirect.added was being remembered between each test and i couldnt figure out how to fix that within jest. i think this will probably be more reliable but yes, it's less clean.
=> hotfix: redirect.added was unreliable espec in tests

lib/helpers/isRouteWithFallback.js, tests/__snapshots__/defaults.test.js.snap, tests/__snapshots__/i18n.test.js.snap, tests/fixtures/pages/getStaticProps/withFallbackBlocking/[id].js
Fixes https://github.com/netlify/next-on-netlify/issues/111
for pages with fallback: "blocking", they're generated into prerender-manifest's `dynamicRoutes` as having `fallback: null`, not `fallback: false`. therefore, our previous check failed to exclude those pages, so anyone trying to use fallback: blocking with NoN would get the next_whatever_page_it_is.js already exists failure.
=> fix: fallback blocking would cause builds to crash

README.md, index.js, lib/config.js, lib/steps/setupImageFunction.js, lib/steps/setupRedirects.js, lib/templates/imageFunction.js, package-lock.json, package.json, tests/__snapshots__/defaults.test.js.snap, tests/__snapshots__/i18n.test.js.snap, tests/__snapshots__/optionalCatchAll.test.js.snap, tests/defaults.test.js, tests/preRenderedIndexPages.test.js, tests/staticIndexPages.test.js
Fixes https://github.com/netlify/next-on-netlify/issues/70
as [this comment](https://github.com/netlify/next-on-netlify/issues/70#issuecomment-724399808) points out, this solution for initial support is not performant because the function will re-run on every request without any caching. that said, this PR is just initial support. we have performance improvements on our roadmap, depending on internal work at netlify. this PR adds this caveat to our README.
my plan, once this PR is merged, is to close #70, open a new issue that addresses performance, and update #70 so anyone from there can follow the new issue.
s/o to @jlengstorf for doing the 90% of work ahead of this PR 🙏
=> initial support for next/image on netlify

index.js, lib/config.js, lib/steps/setupHeaders.js, tests/__snapshots__/defaults.test.js.snap, tests/defaults.test.js
Fixes https://github.com/netlify/next-on-netlify/issues/110
=> generate _headers file to override static chunks cache control

index.js, lib/helpers/handleFileTracking.js, lib/steps/prepareFolders.js, tests/configurableDirs.test.js, tests/helpers/buildNextApp.js
this is a pass at tracking NoN-moved or NoN-generated files between runs of NoN and cleaning them before a new run.
i don't see a way we can add a "manual" clean option for plugin CLI users. for example, if they build on the CLI four consecutive times, this change should allow them to do that without having to change our file overwrite logic at all. BUT, when they're done building/deploying on the CLI, they will be left with all the NoN files in their .git, as @FinnWoelm pointed out in the original issue that has since been transferred internally. because the plugin will only run on `netlify build`, i don't think adding a "clean" flag/command to NoN will make a difference; there'd be no way for the plugin to access it outside of a build. these users will have to stash or manually delete …
=> track NoN files when configured dirs are used, clean before each new run

README.md, lib/helpers/handleFileTracking.js, tests/fixtures/.nonfiletracking
this was the most annoying thing i've ever fixed. probably. it's close. all this file tracking work should be a bandaid anyways so i'm not worrying about the horrific os check :)
=> fix windows test in file tracking work

index.js, tests/defaults.test.js
=> revert next/image support until jimp module issue is resolved

cypress/plugins/deployProject.js, lib/steps/setupHeaders.js, tests/__snapshots__/defaults.test.js.snap
Fixes https://github.com/netlify/next-on-netlify/issues/151
=> remove unneccessary * from headers rule that broke ntl dev

index.js, lib/steps/copyPublicFiles.js
Fixes https://github.com/netlify/next-on-netlify/issues/137
=> prevent copy of .public to .public

cypress/fixtures/pages-with-optionalCatchAll-at-root/[bar]/ssr.js, cypress/fixtures/pages-with-optionalCatchAll-at-root/home.js, cypress/integration/optionalCatchAll_at_root_spec.js, lib/helpers/getSortedRedirects.js, lib/helpers/removeFileExtension.js, lib/steps/copyNextAssets.js, lib/steps/setupRedirects.js, tests/__snapshots__/defaults.test.js.snap, tests/__snapshots__/i18n.test.js.snap, tests/__snapshots__/optionalCatchAll.test.js.snap
Fixes https://github.com/netlify/next-on-netlify/issues/153
as our lovely finn identified yesterday, the isDynamicRoute check we import from serverless-next does not return true for routes ending in `.json` so now we strip the file extensions from the routes before passing them to that check!
thanks to @amuttsch for the detailed issue! :D
=> strip file extension when checking if route is dynamic in setupRedirects

README.md
This draft makes small accessibility changes regarding heading hierarchical headings, and adds a foonote about private submodules.
=> feat: enhance README

README.md
Hi Netlify team! 👋 I was following this great step by step guide to deploy my Next.js website and spotted a few things that could be clearer for first timers or early career devs, like me.
=> Update README with clearer setup/deploy instructions 

README.md, index.js, lib/config.js, lib/helpers/getNextDistDir.js, lib/helpers/getNextSrcDir.js, next-on-netlify.js, package-lock.json, package.json
Fixes https://github.com/netlify/next-on-netlify/issues/96
Opening as draft as I have some questions/clarifications, I'll add those as comments on the PR.
=> feat: add watch mode

README.md, lib/helpers/getNetlifyFunctionName.js, lib/helpers/setupNetlifyFunctionForPage.js, lib/pages/api/redirects.js, lib/pages/api/setup.js, tests/__snapshots__/defaults.test.js.snap, tests/__snapshots__/i18n.test.js.snap, tests/defaults.test.js, tests/fixtures/pages/api/hello-background.js
Fixes https://github.com/netlify/next-on-netlify/issues/166
want to get a range of eyes on this. there is a small risk mentioned in a comment inside regarding users possibly unknowingly creating background functions if theyre not familiar with them and happen to end their api page name in background. this was an ask by one specific user awhile ago and i think, as long as there's no real risk, this would be a great offering. 
for now, i'm omitting an addition to the README documenting this support with a personal task to add it later. would like to run this by docs as well.
=> add support for background functions in api pages only

lib/helpers/copyDynamicImportChunks.js, lib/helpers/setupNetlifyFunctionForPage.js, tests/configurableDirs.test.js, tests/dynamicImports.test.js, tests/fixtures/components/Header.js, tests/fixtures/next.config.js-est, tests/fixtures/pages-dynamic-imports/deep/import.js, tests/fixtures/pages-dynamic-imports/index.js
Fixes https://github.com/netlify/next-on-netlify/issues/121
=> copy dynamic import chunks to functions dirs

README.md
I wanted to install the plugin, but it didn't work because it was not clear this plugin was deprecated. 
So I think it will be a good idea to move the deprecation message on the top, so it's the first thing people see.
If you don't agree, no hard feelings 😅
=> More priority for deprecation
